spring:
  profiles:
    active: cloud
---
spring:
  application:
    name: s3-broker
  profiles: cloud
  datasource:
    url: ${cloud.services.mysql.connection.uri}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    generate-ddl: true
management:
  contextPath: /management
endpoints:
  info:
    enabled: true
security:
  basic:
    enabled: true
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID:replace}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:replace}
broker:
  providerDisplayName: "Amazon S3"
  documentationUrl: "http://aws.amazon.com/s3"
  supportUrl: "http://aws.amazon.com/s3"
  displayName: "Amazon S3"
  longDescription: "A backing service with unlimited Amazon S3 storage"
  imageUrl: "/logo.png"
  basicPlan:
    id: "ac8fdb55-3223-41e9-a5f5-eca6f8fd40c0"
    name: "s3-basic"
    description: "Amazon S3 bucket with unlimited storage"
    free: true
  definition:
    id: "00a3b868-9cf9-4ad3-a6b0-e867740cbef0"
    name: "amazon-s3"
    description: "Amazon S3 simple storage as a backing service"
    bindable: true
---
spring:
  profiles: test
  jpa:
    database: H2
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:h2:mem:db"
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID:replace}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:replace}