spring:
  application:
    name: s3-broker
  profiles: cloud
  datasource:
    url: ${cloud.services.mysql.connection.uri}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    generate-ddl: true
management:
  contextPath: /management
endpoints:
  info:
    enabled: true
security:
  basic:
    enabled: true
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID:replace}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:replace}
---
spring:
  profiles: test
  jpa:
    database: H2
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:h2:mem:db"
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID:replace}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:replace}